Repository twosigma/waiter, pull requests merged in 2018-06, with the labels that each got.

#344 handles NPE while querying for service state before syncer update
  waiter/src/waiter/handler.clj
  waiter/src/waiter/scheduler.clj
  waiter/test/waiter/scheduler_test.clj
Labels: bug

#345 Minor changes
  waiter/src/waiter/mesos/marathon.clj
  waiter/src/waiter/mesos/mesos.clj
  waiter/src/waiter/scaling.clj
Labels: refactoring

#347 Refactors code in scale-app to improve readability
  waiter/src/waiter/scaling.clj
Labels: refactoring

#305 App instance startup metrics
  waiter/integration/waiter/metrics_output_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/metrics.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/state.clj
  waiter/test/waiter/scheduler_test.clj
  waiter/test/waiter/state_test.clj
Labels: metrics

#369 moves retrieve-log-url and retrieve-directory-content-from-host
  waiter/src/waiter/mesos/mesos.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/test/waiter/scheduler/marathon_test.clj
Labels: refactoring

#370 adds missing `mesos-slave-port` and `slave-directory` config to config-full.edn
  waiter/config-full.edn
Labels: refactoring

#368 adds service-id->password-fn in the scheduler context during creation
  waiter/src/waiter/core.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/src/waiter/service.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/scheduler/marathon_test.clj
  waiter/test/waiter/scheduler/shell_test.clj
  waiter/test/waiter/service_test.clj
Labels: refactoring
