Repository twosigma/waiter, pull requests merged in 2018-08, with the labels that each got.

#393 test-grace-period-with-token better handling of non-200 response
  waiter/integration/waiter/request_timeout_test.clj
Labels: test

#397 renames app to service in waiter scheduler and scaler
  waiter/docs/notes/scaling.md
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/scaling.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/cook.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/src/waiter/service.clj
  waiter/src/waiter/simulator.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/handler_test.clj
  waiter/test/waiter/mesos/marathon_test.clj
  waiter/test/waiter/scaling_test.clj
  waiter/test/waiter/scheduler/cook_test.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
  waiter/test/waiter/scheduler/marathon_test.clj
  waiter/test/waiter/scheduler/shell_test.clj
  waiter/test/waiter/scheduler_test.clj
Labels: refactoring

#399 Use utils/map->json to preserve namespaces in k8s spec keys
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
  waiter/test/waiter/util/utils_test.clj
Labels: bug

#401 adds integration test to verify service-id changes when defaults are specified explicitly
  waiter/integration/waiter/basic_test.clj
Labels: test

#408 Adds available service ids in router state maintainer
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/state.clj
  waiter/test/waiter/handler_test.clj
  waiter/test/waiter/state_test.clj
Labels: refactoring

#409 adds support to synchronously query the service state in the autoscaler daemon
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/scaling.clj
  waiter/test/waiter/handler_test.clj
  waiter/test/waiter/scaling_test.clj
Labels: refactoring

#419 sorts map and vector keyword entries in router-state-maintainer
  waiter/src/waiter/state.clj
Labels: refactoring

#411 makes fallback maintainer rely on router-state-maintainer state updates
  waiter/src/waiter/core.clj
  waiter/src/waiter/descriptor.clj
  waiter/test/waiter/descriptor_test.clj
Labels: refactoring

#412 makes interstitial maintainer rely on router-state-maintainer state updates
  waiter/src/waiter/core.clj
  waiter/src/waiter/interstitial.clj
  waiter/test/waiter/interstitial_test.clj
Labels: refactoring

#413 changes service-gc-go-routine to support a function along with a channel to retrieve raw data
  waiter/src/waiter/core.clj
  waiter/src/waiter/metrics.clj
  waiter/src/waiter/scheduler.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/metrics_test.clj
  waiter/test/waiter/scheduler_test.clj
Labels: refactoring

#410 Statsd router state maintainer
  waiter/config-full.edn
  waiter/integration/waiter/statsd_support_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/statsd.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/statsd_test.clj
Labels: refactoring

#425 deflakes test-router-state-maintainer-removes-killed-instances
  waiter/test/waiter/state_test.clj
Labels: flaky-test
