Repository twosigma/waiter, pull requests merged in 2018-04, with the labels that each got.

#260 refactor: rename variables
  waiter/src/waiter/service_description.clj
Labels: refactoring

#265 handles NPE in authentication
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/utils.clj
  waiter/src/waiter/websocket.clj
Labels: bug

#276 Override of lein parallel-test thread count via env
  waiter/project.clj
Labels: refactoring, test

#254 Provide service-description to the service factory
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/main.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/scheduler/marathon_test.clj
  waiter/test/waiter/scheduler/shell_test.clj
  waiter/test/waiter/scheduler_test.clj
Labels: refactoring

#281 Two changes in waiter.state for readability
  waiter/src/waiter/state.clj
Labels: refactoring

#283 Lift symbol resolution into a standalone function
  waiter/src/waiter/utils.clj
Labels: refactoring

#284 Simplify Leiningen usage in Travis-CI
  .travis.yml
  waiter/bin/ci/install-lein
Labels: refactoring

#282 Token etag to hash rename
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/token.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/token_test.clj
Labels: refactoring

#288 renames tokens to service-description-template
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: refactoring

#290 ensures presence of only param headers does not cause service to become unauthorized
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: bug

#294 Renames apps to services in scheduler messages
  waiter/src/waiter/interstitial.clj
  waiter/src/waiter/metrics.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/state.clj
  waiter/src/waiter/statsd.clj
  waiter/test/waiter/interstitial_test.clj
  waiter/test/waiter/metrics_test.clj
  waiter/test/waiter/scheduler_test.clj
  waiter/test/waiter/state_test.clj
  waiter/test/waiter/statsd_test.clj
Labels: refactoring

#295 corrects name from token-description to token-data
  waiter/src/waiter/token.clj
Labels: refactoring

#298 introduces the `date-utils` class
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/instance_reservation_test.clj
  waiter/integration/waiter/token_request_test.clj
  waiter/integration/waiter/websocket_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/main.clj
  waiter/src/waiter/metrics_sync.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/request_log.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/src/waiter/state.clj
  waiter/src/waiter/statsd.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/date_utils.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/metrics_sync_test.clj
  waiter/test/waiter/scheduler/marathon_test.clj
  waiter/test/waiter/scheduler_test.clj
  waiter/test/waiter/state_test.clj
  waiter/test/waiter/token_test.clj
  waiter/test/waiter/util/utils_test.clj
Labels: refactoring

#299 respects descriptor present in the response while wrapping the descriptor
  waiter/src/waiter/middleware.clj
  waiter/src/waiter/process_request.clj
Labels: refactoring

#301 uses wrap-descriptor logic for resolving service id in the /service-id endpoint
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
Labels: refactoring

#287 Allows token-syncer to update previously soft-deleted tokens
  token-syncer/integration/token_syncer/basic_test.clj
  token-syncer/src/token_syncer/commands/syncer.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: bug
