Repository twosigma/waiter, pull requests merged in 2019-07, with the labels that each got.

#827 ensures response trailers are always non-empty
  waiter/integration/waiter/trailers_test.clj
  waiter/project.clj
Labels: internal-green

#831 adds blocking-timeout to server-options
  waiter/config-full.edn
  waiter/project.clj
  waiter/src/waiter/settings.clj
Labels: internal-green

#775 delete run-integration-tests-shell-scheduler
  waiter/bin/ci/run-integration-tests-shell-scheduler.sh
Labels: internal-green

#802 fix integration test and clean up tokens
  waiter/integration/waiter/authentication_test.clj
Labels: internal-green

#820 adds parallel streaming tests for http and h2 connections to backends
  containers/test-apps/nginx/data/nginx-template.conf
  waiter/integration/waiter/content_encoding_test.clj
  waiter/integration/waiter/proto_test.clj
  waiter/src/waiter/core.clj
Labels: internal-green

#841 Rethrow all Throwables in async get-available-instance thread
  waiter/src/waiter/service.clj
Labels: internal-green

#843 adds support for asynchronous reads using the ReadListener from servlet api
  waiter/config-full.edn
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/streaming_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/settings.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#845 Fix trailers_test
  waiter/integration/waiter/trailers_test.clj
Labels: internal-green

#814 removes unused imports of sling try+
  waiter/src/waiter/core.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/util/async_utils.clj
  waiter/src/waiter/websocket.clj
Labels: internal-green

#838 Add current-for-tokens
  waiter/bin/run-using-marathon.sh
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/test/waiter/core_test.clj
Labels: internal-green

#844 adds support for propagating grpc server-side cancellations
  containers/test-apps/courier/pom.xml
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/GrpcClient.java
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/GrpcServer.java
  containers/test-apps/courier/src/main/proto/courier.proto
  waiter/integration/waiter/grpc_test.clj
  waiter/project.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#836 Make python idp server
  containers/test-apps/saml/idpserver/.gitignore
  containers/test-apps/saml/idpserver/README.md
  containers/test-apps/saml/idpserver/bin/run-idp-server
  containers/test-apps/saml/idpserver/python/idp_server.py
  containers/test-apps/saml/idpserver/requirements.txt
  containers/test-apps/saml/idpserver/resources/idp.crt
  containers/test-apps/saml/idpserver/resources/privatekey.pem
  containers/test-apps/saml/idpserver/resources/saml-response-redirect-template.html
  containers/test-apps/saml/idpserver/resources/saml-response-template.xml
  waiter/bin/ci/run-integration-tests-composite-scheduler.sh
  waiter/bin/ci/saml-idp-server-setup.sh
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#856 Adds metrics collection to integration tests
  waiter/project.clj
  waiter/test/waiter/test_helpers.clj
  waiter/test/waiter/test_metrics_test.clj
Labels: internal-green

#861 Adds run-description to test metrics collection
  waiter/test/waiter/test_helpers.clj
Labels: internal-green

#863 Report GSS Exceptions as 403 errors (not 500)
  waiter/src/waiter/auth/spnego.clj
Labels: internal-green

#859 Add service description builder state
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#858 disable flaky tests only on kubernetes
  waiter/integration/waiter/proto_test.clj
Labels: internal-green

#864 make tests compatible with composite scheduler
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/integration/waiter/latency_test.clj
  waiter/integration/waiter/request_timeout_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#865 adds support for logging request trailers
  waiter/src/waiter/process_request.clj
Labels: internal-green

#862 performs cleanup of request body channels when frontend request completes
  waiter/integration/waiter/streaming_test.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#811 shortens integration test CIDs
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#867 avoids races in interstitial metrics that end up affecting other unit tests
  waiter/test/waiter/interstitial_test.clj
  waiter/test/waiter/metrics_test.clj
  waiter/test/waiter/reporters_test.clj
  waiter/test/waiter/test_helpers.clj
Labels: flaky-test, internal-green

#830 disables sending trailers to non-http/2 backends
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/trailers_test.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#873 truncates authorization and cookie values in kitchen request-info response
  containers/test-apps/kitchen/bin/kitchen
  waiter/integration/waiter/cookie_support_integration_test.clj
Labels: internal-green

#870 courier: adds support for client-side cancellations and deadlines
  containers/test-apps/courier/pom.xml
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/GrpcClient.java
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/GrpcServer.java
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/LoggingConfig.java
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/Main.java
  containers/test-apps/courier/src/main/proto/courier.proto
Labels: internal-green

#871 refactor grpc tests to include grpc state transitions
  waiter/integration/waiter/grpc_test.clj
  waiter/project.clj
Labels: internal-green, refactoring, test

#868 Handle case when suggested instance is nil
  waiter/src/waiter/process_request.clj
Labels: internal-green

#809 Eagerly upload completed container logs to S3
  containers/fileserver/Dockerfile
  containers/fileserver/fileserver-start
  containers/fileserver/s3-log-backup
  containers/test-apps/waiter-init/bin/test-waiter-k8s-init
  containers/test-apps/waiter-init/bin/waiter-k8s-init
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#875 Handle nil start timestamps for failed Kubernetes instances
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/src/waiter/util/date_utils.clj
Labels: internal-green

#876 enables proto tests
  waiter/integration/waiter/proto_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#771 Fix deep-merge-settings
  waiter/src/waiter/settings.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/settings_test.clj
Labels: internal-green

#879 Catch and log errors in k8s track-failed-instances fn
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: internal-green

#878 adds logging of request trailers
  waiter/src/waiter/core.clj
Labels: internal-green

#881 tags response when they are generated by the waiter router
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/main.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/auth/spnego_test.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/test_helpers.clj
Labels: internal-green, refactoring

#886 wrap test metrics in try catch
  waiter/test/waiter/test_helpers.clj
Labels: internal-green

#880 updates jet version for fix for response trailers and body streaming race
  waiter/project.clj
Labels: internal-green

#883 explicitly classify error cause during request/response streaming
  waiter/src/waiter/process_request.clj
Labels: internal-green

#872 adds support for grpc-status on waiter generated responses
  waiter/integration/waiter/grpc_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/main.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/core_test.clj
Labels: internal-green

#884 aborts backend requests using the abort-ch - v2
  waiter/project.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/scheduler.clj
  waiter/test/waiter/scheduler_test.clj
Labels: internal-green

#888 removes chime as a dependency
  waiter/project.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/util/async_utils.clj
  waiter/src/waiter/util/date_utils.clj
  waiter/test/waiter/util/async_utils_test.clj
  waiter/test/waiter/util/date_utils_test.clj
  waiter/test/waiter/util/utils_test.clj
Labels: internal-green

#889 Run test-s3-logs only when log-bucket-url is configured
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
Labels: internal-green

#891 renames http-utils alias to hu
  waiter/src/waiter/core.clj
  waiter/src/waiter/mesos/marathon.clj
  waiter/src/waiter/mesos/mesos.clj
  waiter/src/waiter/scheduler/cook.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/mesos/marathon_test.clj
  waiter/test/waiter/mesos/mesos_test.clj
  waiter/test/waiter/scheduler/cook_test.clj
Labels: internal-green, refactoring

#890 removes middleware to generate grpc responses
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/main.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/http_utils.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/auth/spnego_test.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/util/utils_test.clj
Labels: internal-green, refactoring
