Repository twosigma/waiter, pull requests merged in 2019-08, with the labels that each got.

#897 Include pod logs in Travis logs tarball
  waiter/bin/ci/run-integration-tests-k8s-scheduler.sh
  waiter/bin/ci/s3-server-setup.sh
  waiter/bin/ci/upload-logs.sh
Labels: internal-green

#898 Deflake s3-logs test by targeting a router
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#896 makes assert-ping-response less flaky
  waiter/integration/waiter/health_check_test.clj
Labels: flaky-test

#885 adds support for grpc client deadline
  waiter/integration/waiter/grpc_test.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#901 adds errors to assertion responses
  waiter/integration/waiter/proto_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#893 add failed tests file support
  waiter/test/waiter/test_helpers.clj
Labels: internal-green

#907 ensures the server header gets added to the request log for waiter generated responses
  waiter/integration/waiter/request_timeout_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/main.clj
Labels: internal-green, regression

#908 adds state and unknown host for marathon instances
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/test/waiter/scheduler/marathon_test.clj
  waiter/test/waiter/scheduler_test.clj
Labels: internal-green

#909 adds state for kubernetes instances
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#900 increases upper-limit of scale-factor to 2.0
  waiter/docs/parameters.md
  waiter/src/waiter/scaling.clj
  waiter/src/waiter/schema.clj
  waiter/src/waiter/service_description.clj
Labels: internal-green

#911 Use lein parallel-test v0.3.2
  waiter/project.clj
Labels: internal-green

#912 includes all container statuses in k8s instances
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#887 adds integration test for clients that cancel via process exit
  containers/test-apps/courier/pom.xml
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/GrpcClient.java
  waiter/integration/waiter/grpc_test.clj
  waiter/project.clj
  waiter/test-files/grpc/grpc_client_exit.clj
Labels: internal-green

#910 propagate metrics of all running services across routers
  waiter/src/waiter/scheduler.clj
  waiter/test/waiter/scheduler_test.clj
Labels: internal-green

#892 adds support for grpc client cancellations via api calls
  waiter/integration/waiter/grpc_test.clj
  waiter/integration/waiter/proto_test.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#904 includes pods in container creating phase as unhealthy instances
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/state.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#913 assigns unique metrics registry in unit tests
  waiter/test/waiter/metrics_test.clj
Labels: flaky-test, internal-green

#916 add eftest
  waiter/project.clj
Labels: internal-green

#917 includes unhealthy instances while computing expired instances
  waiter/config-full.edn
  waiter/src/waiter/core.clj
  waiter/src/waiter/scaling.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/state.clj
  waiter/test/waiter/scaling_test.clj
  waiter/test/waiter/state_test.clj
Labels: internal-green

#918 moves x-waiter-auth cookie validation into a single handler
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/auth/saml.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/core.clj
  waiter/test/waiter/auth/authenticator_test.clj
  waiter/test/waiter/auth/saml_test.clj
  waiter/test/waiter/auth/spnego_test.clj
  waiter/test/waiter/core_test.clj
Labels: internal-green

#919 Ignore .test_metrics directory
  waiter/.gitignore
Labels: internal-green

#906 expires kubernetes services instances stuck in non-running state
  waiter/bin/ci/run-integration-tests-k8s-scheduler.sh
  waiter/config-full.edn
  waiter/config-k8s.edn
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/settings.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#921 Support annotating a Waiter pod as expired
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#920 add test metrics to CLI tests
  cli/integration/setup.cfg
  cli/integration/tests/__init__.py
  cli/integration/tests/conftest.py
  cli/integration/tests/waiter/__init__.py
  waiter/project.clj
  waiter/test/waiter/test_helpers.clj
Labels: internal-green

#924 adds authentication source to the request log
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/auth/saml.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/request_log.clj
  waiter/src/waiter/websocket.clj
  waiter/test/waiter/auth/authenticator_test.clj
  waiter/test/waiter/auth/saml_test.clj
  waiter/test/waiter/auth/spnego_test.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/request_log_test.clj
  waiter/test/waiter/websocket_test.clj
Labels: internal-green

#925 introduces x-waiter-auth headers in /waiter-auth
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/core.clj
Labels: internal-green

#926 lexicographic ordering of launch-metrics
  waiter/src/waiter/core.clj
Labels: internal-green, refactoring

#929 adds instance backend-proto to the request log
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/request_log.clj
  waiter/test/waiter/request_log_test.clj
Labels: internal-green

#927 adds kubernetes pod name to the request log
  waiter/src/waiter/request_log.clj
  waiter/test/waiter/request_log_test.clj
Labels: internal-green

#928 adds kubernetes node name to the request log
  waiter/src/waiter/request_log.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/request_log_test.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#931 upgrades jetty version to 9.4.20.v20190813
  waiter/integration/waiter/grpc_test.clj
  waiter/project.clj
Labels: internal-green

#914 includes explanation in CORS denied response
  waiter/src/waiter/cors.clj
  waiter/test/waiter/cors_test.clj
Labels: internal-green

#930 Allows both --json and token args on create/update
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/token_post.py
Labels: cli, enhancement, internal-green

#933 Updates Waiter CLI version
  cli/waiter/version.py
Labels: cli, internal-green

#932 removes clojurescript dependencies
  waiter/project.clj
Labels: internal-green

#938 Marks two integration tests ^:explicit
  waiter/integration/waiter/grpc_test.clj
  waiter/integration/waiter/proto_test.clj
Labels: flaky-test, test

#939 clears the token index when the owner of a deleted token changes
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: bug, internal-green

#937 fixes websocket connection for authentication disabled
  waiter/integration/waiter/websocket_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/websocket.clj
  waiter/test/waiter/websocket_test.clj
Labels: internal-green

#935 Self service CORS
  waiter/config-full.edn
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/cors.clj
  waiter/src/waiter/main.clj
  waiter/src/waiter/schema.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/token.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/cors_test.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green
