Repository twosigma/waiter, pull requests merged in 2019-05, with the labels that each got.

#725 adds support for request and response content-type in the request log
  waiter/src/waiter/request_log.clj
  waiter/test/waiter/request_log_test.clj
Labels: internal-green

#723 X-Waiter-Namespace
  waiter/bin/ci/minikube-setup.sh
  waiter/bin/ci/monitor-pods.sh
  waiter/config-full.edn
  waiter/config-k8s.edn
  waiter/docs/parameters.md
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/headers.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
  waiter/test/waiter/scheduler/marathon_test.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#724 Sends x-cid from the CLI and its tests
  cli/integration/tests/waiter/util.py
  cli/waiter/http_util.py
Labels: cli, internal-green

#722 Makes test_ping_basic more reliable
  cli/integration/tests/waiter/test_cli.py
  cli/integration/tests/waiter/util.py
Labels: cli, flaky-test, internal-green, test

#727 adds h2c and h2c request handling tests
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/trailers_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#729 avoids 500 error when invalid owner name is provided
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#730 Upstream/code lint
  waiter/integration/waiter/deployment_errors_test.clj
  waiter/integration/waiter/instability_test.clj
  waiter/integration/waiter/token_request_test.clj
  waiter/integration/waiter/work_stealing_integration_test.clj
  waiter/src/waiter/async_request.clj
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/auth/kerberos.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/authorization.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/cors.clj
  waiter/src/waiter/curator.clj
  waiter/src/waiter/headers.clj
  waiter/src/waiter/metrics.clj
  waiter/src/waiter/metrics_sync.clj
  waiter/src/waiter/reporter.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/cook.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/state.clj
  waiter/src/waiter/token.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/cookie_support_test.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/curator_test.clj
  waiter/test/waiter/dummy_test.clj
  waiter/test/waiter/metrics_sync_test.clj
  waiter/test/waiter/mocks.clj
  waiter/test/waiter/request_log_test.clj
  waiter/test/waiter/scheduler/cook_test.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
  waiter/test/waiter/schema_test.clj
  waiter/test/waiter/state_service_responder_test.clj
  waiter/test/waiter/state_test.clj
  waiter/test/waiter/token_test.clj
  waiter/test/waiter/zk_test.clj
Labels: internal-green

#731 avoids fatal error for services with unknown service descriptions
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/state.clj
  waiter/test/waiter/service_description_test.clj
  waiter/test/waiter/state_test.clj
Labels: internal-green

#726 Removes token name validation from fetch path
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#732 Exclude k8s service account injection for default namespace
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: internal-green

#733 Uses 'Current' and 'Not Current' for the services table
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/subcommands/show.py
Labels: cli, internal-green

#734 CLI version 0.3.0
  cli/waiter/version.py
Labels: cli, internal-green

#735 Disable h2c tests
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/trailers_test.clj
Labels: internal-green, test

#740 updates jet to 0.7.10-20190508_061258-gebd9d0a
  waiter/project.clj
Labels: internal-green

#741 Makes test_kill_timeout more reliable
  cli/integration/tests/waiter/test_cli.py
Labels: cli, flaky-test, internal-green, test

#739 avoids TE hop-by-hop removal for grpc requests
  waiter/src/waiter/headers.clj
  waiter/test/waiter/headers_test.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#742 Adds logging and checks to util.post_token
  cli/integration/tests/waiter/util.py
  waiter/integration/waiter/websocket_integration_test.clj
Labels: cli, flaky-test, internal-green, test

#743 Allows providing token JSON from stdin
  cli/integration/tests/waiter/cli.py
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/token_post.py
Labels: cli, enhancement, internal-green

#744 Bumps CLI version to 0.4.0
  cli/waiter/version.py
Labels: cli, internal-green

#747 avoids sending custom user-agent headers to the backend
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/core.clj
Labels: internal-green

#736 Add JSON spec to create Kitchen service via waiter cli
  containers/test-apps/kitchen/README.md
  containers/test-apps/kitchen/kitchen.json
Labels: internal-green

#745 Allow k8s namespace with run-as-requestor
  waiter/docs/parameters.md
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#749 Adds --no-wait to waiter ping
  cli/integration/tests/waiter/test_cli.py
  cli/integration/tests/waiter/util.py
  cli/waiter/subcommands/ping.py
  cli/waiter/subcommands/show.py
  cli/waiter/util.py
Labels: cli, enhancement, internal-green

#750 Improves CLI's implicit arg handling
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/cli.py
  cli/waiter/token_post.py
Labels: cli, enhancement, internal-green

#753 Updates CLI version to 0.5.0
  cli/waiter/version.py
Labels: cli, internal-green

#751 supports reading the input stream in custom thread pool
  waiter/config-full.edn
  waiter/project.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/settings.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#755 adds support for naming http clients
  waiter/project.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/scheduler/cook.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/http_utils.clj
Labels: internal-green

#757 avoids folding chunked responses for http/2
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/util/http_utils.clj
Labels: internal-green

#754 Makes test_show_service_current more reliable
  cli/integration/tests/waiter/cli.py
  cli/integration/tests/waiter/test_cli.py
  waiter/integration/waiter/basic_test.clj
Labels: cli, flaky-test, internal-green, test

#756 minimizes redundant puts into the body channel
  waiter/src/waiter/process_request.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green, refactoring

#758 Includes request length in chunked encoding tests
  containers/test-apps/kitchen/bin/kitchen
  waiter/integration/waiter/basic_test.clj
Labels: internal-green

#761 deletes tokens created in test-service-list-filtering
  waiter/integration/waiter/token_request_test.clj
Labels: internal-green

#762 deletes token created in test-valid-fallback-service-resolution
  waiter/integration/waiter/token_request_test.clj
Labels: internal-green

#760 moves backend and health check proto tests to proto_test.clj
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/proto_test.clj
Labels: internal-green, refactoring

#764 introduces a delay before failing requests due to back pressure in streaming request bytes
  waiter/src/waiter/process_request.clj
Labels: internal-green

#766 adds support for delayed scheduler synced results in ping tests
  waiter/integration/waiter/health_check_test.clj
Labels: flaky-test, internal-green

#765 adds support for filtering metrics by name
  waiter/integration/waiter/metrics_output_test.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/metrics.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/metrics_test.clj
Labels: internal-green

#767 uses bitwise operators while computing buffer size
  waiter/src/waiter/process_request.clj
Labels: internal-green, refactoring

#769 adds grpc status to the request log
  waiter/src/waiter/request_log.clj
  waiter/test/waiter/request_log_test.clj
Labels: internal-green

#772 propagate exception cause better
  waiter/src/waiter/util/utils.clj
Labels: internal-green

#770 Fixes bug in ping due to connection error
  cli/waiter/subcommands/ping.py
Labels: bug, cli, internal-green

#773 adds the service description to the ping response
  waiter/integration/waiter/health_check_test.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#774 adds principal and backend properties to the request log for waiter-ping
  waiter/integration/waiter/health_check_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#778 marks test-s3-logs as explicit
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
Labels: flaky-test, internal-green

#777 Minor integration test changes
  waiter/integration/waiter/health_check_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green
