Repository twosigma/waiter, pull requests merged in 2019-09, with the labels that each got.

#940 cleanup trailer support after jetty upgrade
  waiter/integration/waiter/trailers_test.clj
  waiter/project.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green, tech-debt

#936 adds support for randomly selecting instances while not scaling down
  waiter/config-full.edn
  waiter/docs/parameters.md
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/instance_reservation_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/headers.clj
  waiter/src/waiter/scaling.clj
  waiter/src/waiter/schema.clj
  waiter/src/waiter/service.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/state.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/handler_test.clj
  waiter/test/waiter/scaling_test.clj
  waiter/test/waiter/service_test.clj
  waiter/test/waiter/state_service_responder_test.clj
  waiter/test/waiter/state_test.clj
Labels: internal-green

#946 refactors descriptor to allow retrieving previous-descriptor from multiple sources
  waiter/src/waiter/descriptor.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/descriptor_test.clj
Labels: internal-green

#944 Add support for multiple listening ports
  waiter/integration/waiter/basic_test.clj
  waiter/project.clj
  waiter/resources/web/welcome.html
  waiter/resources/web/welcome.txt
  waiter/src/waiter/core.clj
  waiter/src/waiter/settings.clj
Labels: internal-green

#923 adds support for JWT access tokens
  containers/test-apps/jwks-server/.gitignore
  containers/test-apps/jwks-server/README.md
  containers/test-apps/jwks-server/project.clj
  containers/test-apps/jwks-server/resources/jwks.json
  containers/test-apps/jwks-server/resources/log4j.properties
  containers/test-apps/jwks-server/resources/settings.edn
  containers/test-apps/jwks-server/src/jwks_server/config.clj
  containers/test-apps/jwks-server/src/jwks_server/handler.clj
  containers/test-apps/jwks-server/src/jwks_server/main.clj
  waiter/bin/ci/jwks-server-setup.sh
  waiter/bin/ci/run-integration-tests-composite-scheduler.sh
  waiter/bin/ci/run-integration-tests-k8s-scheduler.sh
  waiter/bin/ci/run-integration-tests-marathon-scheduler.sh
  waiter/config-composite.edn
  waiter/config-full.edn
  waiter/config-k8s.edn
  waiter/config-minimal.edn
  waiter/config-minimesos.edn
  waiter/config-shell.edn
  waiter/integration/waiter/authentication_test.clj
  waiter/project.clj
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/auth/jwt.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/schema.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/ring_utils.clj
  waiter/test-files/jwt/jwks.json
  waiter/test/waiter/auth/authenticator_test.clj
  waiter/test/waiter/auth/jwt_test.clj
  waiter/test/waiter/auth/spnego_test.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/settings_test.clj
Labels: internal-green

#948 More time for log files to appear in S3 for test
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
Labels: internal-green

#947 adds endpoint to visualize work-stealing metrics
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/metrics.clj
  waiter/src/waiter/work_stealing.clj
Labels: internal-green

#945 limits the maximum number of work-stealing offers in-flight from a router
  waiter/config-full.edn
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/util/semaphore.clj
  waiter/src/waiter/work_stealing.clj
  waiter/test/waiter/util/semaphore_test.clj
  waiter/test/waiter/work_stealing_test.clj
Labels: internal-green

#950 moves sanitize-history to utils
  waiter/src/waiter/token.clj
  waiter/src/waiter/util/utils.clj
Labels: internal-green, refactoring

#951 adds assertions and preconditions to some of the integration tests
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/token_request_test.clj
Labels: flaky-test, internal-green

#955 Update kv.clj
  waiter/src/waiter/kv.clj
Labels: bug

#953 removes dependency on state from curator
  waiter/src/waiter/core.clj
  waiter/src/waiter/kv.clj
  waiter/src/waiter/main.clj
  waiter/test/waiter/core_test.clj
Labels: internal-green, refactoring

#954 allows service description builder to contribute to component->previous-descriptor-fns
  waiter/src/waiter/descriptor.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/descriptor_test.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green, refactoring

#959 adds kv-store and leadership operations in the service description builder
  waiter/src/waiter/core.clj
Labels: internal-green

#961 handles multiple ports in waiter settings
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#963 fixes retrieve-most-recently-modified-token-update-time
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: bug, internal-green

#964 makes test-list-apps less flaky
  waiter/integration/waiter/basic_test.clj
Labels: flaky-test, internal-green

#965 improves CORS preflight check
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/cors.clj
  waiter/test/waiter/cors_test.clj
Labels: bug, internal-green

#957 waits for scaling state to become available on the service endpoint on all routers
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: flaky-test, internal-green

#968 excludes command parameter from token
  cli/integration/tests/waiter/test_cli.py
  waiter/integration/waiter/token_request_test.clj
Labels: internal-green

#967 updates jet to 0.7.10-20190924_091442-gfccc405
  waiter/project.clj
Labels: internal-green

#969 makes JWT auth per request opt-in by tokens
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/auth/jwt.clj
  waiter/test/waiter/auth/jwt_test.clj
Labels: internal-green

#970 cleanup imports and unused variables
  waiter/integration/waiter/authentication_test.clj
  waiter/integration/waiter/cookie_support_integration_test.clj
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/integration/waiter/request_timeout_test.clj
  waiter/src/waiter/auth/composite.clj
  waiter/src/waiter/auth/saml.clj
  waiter/src/waiter/authorization.clj
  waiter/src/waiter/reporter.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/auth/saml_test.clj
  waiter/test/waiter/process_request_test.clj
  waiter/test/waiter/reporters_test.clj
  waiter/test/waiter/schema_test.clj
  waiter/test/waiter/test_helpers.clj
Labels: internal-green
