Repository twosigma/waiter, pull requests merged in 2019-06, with the labels that each got.

#703 Adds gGRPC example service and integration test
  containers/test-apps/Dockerfile
  containers/test-apps/README.md
  containers/test-apps/bin/build-docker-image.sh
  containers/test-apps/courier/.gitignore
  containers/test-apps/courier/README.md
  containers/test-apps/courier/bin/run-courier-server.sh
  containers/test-apps/courier/pom.xml
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/GrpcClient.java
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/GrpcServer.java
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/HealthCheckServer.java
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/Main.java
  containers/test-apps/courier/src/main/proto/courier.proto
  waiter/bin/ci/run-integration-tests-composite-scheduler.sh
  waiter/bin/ci/run-integration-tests-k8s-scheduler.sh
  waiter/bin/ci/run-integration-tests-marathon-scheduler.sh
  waiter/bin/ci/run-integration-tests-shell-scheduler.sh
  waiter/integration/waiter/grpc_test.clj
  waiter/integration/waiter/proto_test.clj
  waiter/integration/waiter/trailers_test.clj
  waiter/project.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#779 Update Kubernetes object labels
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#746 Add saml auth
  waiter/bin/ci/run-integration-tests-composite-scheduler.sh
  waiter/bin/ci/saml-idp-server-setup.sh
  waiter/config-composite.edn
  waiter/config-full.edn
  waiter/docs/parameters.md
  waiter/integration/waiter/authentication_test.clj
  waiter/project.clj
  waiter/resources/auth/authenticated-redirect.html
  waiter/resources/auth/saml-authentication-request.xml
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/auth/composite.clj
  waiter/src/waiter/auth/saml.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/cookie_support.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/schema.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/utils.clj
  waiter/test-files/saml/idp.crt
  waiter/test-files/saml/saml-response.txt
  waiter/test-files/saml/saml-response.xml
  waiter/test-files/saml/x509-certificate-to-string.txt
  waiter/test/waiter/auth/composite_test.clj
  waiter/test/waiter/auth/saml_test.clj
  waiter/test/waiter/cookie_support_test.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/settings_test.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#783 Adds support for publishing CLI to pypi
  cli/README.md
  cli/setup.py
  cli/waiter/version.py
Labels: cli, internal-green

#785 updates jet to include implementation of onStartAsync()
  waiter/project.clj
Labels: internal-green

#784 avoids name conflicts with clojure.core error-handler
  waiter/src/waiter/process_request.clj
Labels: internal-green

#789 handles exceptions reported in ctrl channel
  waiter/project.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#781 updates jet dependency to handle NoSuchElementException from DeferredContentProviderIterator
  waiter/project.clj
Labels: internal-green

#763 Uses /waiter-ping endpoint from CLI ping
  cli/integration/tests/waiter/test_cli.py
  cli/integration/tests/waiter/util.py
  cli/waiter/subcommands/ping.py
Labels: cli, internal-green

#791 Makes test_kill_services_sorted more reliable
  cli/integration/tests/waiter/test_cli.py
  cli/integration/tests/waiter/util.py
Labels: cli, flaky-test, internal-green, test

#793 Makes waiter ping default be 5 minutes
  cli/waiter/subcommands/ping.py
Labels: cli, internal-green

#794 Bumps CLI version to 0.6.0
  cli/waiter/version.py
Labels: cli, internal-green

#782 verifies support for temporarily unhealthy instances
  containers/test-apps/kitchen/bin/kitchen
  waiter/integration/waiter/health_check_test.clj
Labels: internal-green

#797 upgrades to jetty version 9.4.19.v20190610
  waiter/project.clj
Labels: internal-green

#795 Use lower-case headers consistently
  waiter/config-full.edn
  waiter/docs/how-to-waiter.md
  waiter/docs/parameters.md
  waiter/docs/rest-api.md
  waiter/integration/waiter/authentication_test.clj
  waiter/integration/waiter/busy_instance_test.clj
  waiter/integration/waiter/streaming_test.clj
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/cors.clj
  waiter/src/waiter/simulator.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/auth/spnego_test.clj
  waiter/test/waiter/cors_test.clj
  waiter/test/waiter/util/utils_test.clj
Labels: internal-green, refactoring

#800 allow min-instances up to 4
  waiter/docs/parameters.md
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#768 WIP: enables http2 integration tests
  waiter/integration/waiter/grpc_test.clj
  waiter/integration/waiter/proto_test.clj
  waiter/integration/waiter/trailers_test.clj
Labels: internal-green

#801 use the session-not-on-or-after field for auth expiry time
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/auth/saml.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/auth/saml_test.clj
  waiter/test/waiter/util/client_tools_test.clj
Labels: internal-green

#803 handles blacklist on 503 for grpc responses
  waiter/src/waiter/headers.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/util/http_utils.clj
  waiter/test/waiter/util/http_utils_test.clj
Labels: internal-green

#804 avoids IllegalStateException due to ReadListener already being set
  waiter/integration/waiter/streaming_test.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#799 Limiting k8s pod restarts using expired instances machinery
  waiter/config-full.edn
  waiter/config-k8s.edn
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/state.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
  waiter/test/waiter/state_test.clj
Labels: internal-green

#805 Adds back pressure for streaming request bytes
  waiter/src/waiter/process_request.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#806 disables assertion in test-streaming for multi-router scenario
  waiter/integration/waiter/streaming_test.clj
Labels: flaky-test, internal-green

#807 uses status code of 503 for request streaming timeout
  waiter/src/waiter/process_request.clj
Labels: internal-green

#808 makes test-kubernetes-pod-expiry less flaky
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: flaky-test, internal-green

#813 corrects default exception handler for exceptions thrown from sling
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: bug, internal-green

#816 Handle missing service on k8s delete
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#817 test-pod-namespace is slow
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
Labels: internal-green

#823 adds request and response content-length header to request log
  waiter/src/waiter/request_log.clj
  waiter/test/waiter/request_log_test.clj
Labels: internal-green

#822 logging and import cleanup in process_request.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#826 leftover changes from PR 746
  waiter/config-full.edn
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test-files/saml/x509-certificate-to-string.txt
Labels: internal-green

#828 configures idle timeout on the http/2 clients used by waiter
  waiter/src/waiter/util/http_utils.clj
Labels: internal-green

#824 refactors test-delete-service
  waiter/integration/waiter/basic_test.clj
Labels: flaky-test, internal-green

#819 accepts any content from the backend health check
  waiter/src/waiter/process_request.clj
Labels: internal-green

#815 improves header value assertion messages
  waiter/integration/waiter/content_encoding_test.clj
Labels: internal-green

#829 do not return 404 for token with only user-specified metadata
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: bug, internal-green
