Repository twosigma/waiter, pull requests merged in 2020-06, with the labels that each got.

#1110 Removed old waiter-cluster label from kubernetes.clj and kubernetes-t…
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1115 removes use of PyInstaller to build the CLI
  cli/bin/ci/setup.sh
Labels: internal-green

#1120 refactor scaling-for-service-test to use parallelize-requests
  waiter/integration/waiter/autoscaling_test.clj
Labels: internal-green, refactoring

#1114 account for token edits while GC-ing services
  waiter/integration/waiter/new_app_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/scheduler_test.clj
  waiter/test/waiter/service_description_test.clj
Labels: bug, internal-green

#1118 work-stealing changes: enable for specific services and configurable offer timeouts
  waiter/config-full.edn
  waiter/integration/waiter/work_stealing_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/work_stealing.clj
  waiter/test/waiter/handler_test.clj
  waiter/test/waiter/work_stealing_test.clj
Labels: bug, internal-green

#1108 adds support for owner flag in create/update help output
  cli/waiter/token_post.py
Labels: internal-green

#1096 OIDC Authentication using Auth Code Flow + PKCE
  containers/test-apps/jwks-server/resources/jwks.json
  containers/test-apps/jwks-server/src/jwks_server/handler.clj
  waiter/bin/ci/run-integration-tests-composite-scheduler.sh
  waiter/bin/ci/run-integration-tests-k8s-scheduler.sh
  waiter/bin/ci/run-integration-tests-marathon-scheduler.sh
  waiter/config-composite.edn
  waiter/config-full.edn
  waiter/config-k8s.edn
  waiter/config-minimesos.edn
  waiter/docs/authentication-decision-tree.dot
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/auth/jwt.clj
  waiter/src/waiter/auth/oidc.clj
  waiter/src/waiter/cookie_support.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/schema.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/http_utils.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/auth/jwt_test.clj
  waiter/test/waiter/auth/oidc_test.clj
  waiter/test/waiter/auth/saml_test.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/settings_test.clj
  waiter/test/waiter/util/http_utils_test.clj
Labels: internal-green

#1122 avoid editing OIDC token specified in the environment
  waiter/integration/waiter/authentication_test.clj
Labels: internal-green

#1124 adds support for query string in the websocket upgrade request
  waiter/integration/waiter/websocket_integration_test.clj
  waiter/src/waiter/websocket.clj
  waiter/test/waiter/websocket_test.clj
Labels: bug, internal-green

#1125 uses latest routers while computing instance distribution
  waiter/src/waiter/state/maintainer.clj
  waiter/test/waiter/state/maintainer_test.clj
Labels: bug, internal-green

#1126 moves service validation so that errors are propagated to the client
  waiter/src/waiter/scheduler/marathon.clj
  waiter/test/waiter/scheduler/marathon_test.clj
Labels: bug, internal-green

#1127 Refactored k8s data shape of (:service-id transient-store)
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: internal-green

#1128 Formats imports
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/grpc_test.clj
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/integration/waiter/marathon_scheduler_integration_test.clj
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/auth/kerberos.clj
  waiter/src/waiter/auth/saml.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/correlation_id.clj
  waiter/src/waiter/cors.clj
  waiter/src/waiter/curator.clj
  waiter/src/waiter/descriptor.clj
  waiter/src/waiter/discovery.clj
  waiter/src/waiter/headers.clj
  waiter/src/waiter/kv.clj
  waiter/src/waiter/main.clj
  waiter/src/waiter/metrics.clj
  waiter/src/waiter/metrics_sync.clj
  waiter/src/waiter/middleware.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/reporter.clj
  waiter/src/waiter/scaling.clj
  waiter/src/waiter/state/responder.clj
  waiter/src/waiter/state/router.clj
  waiter/src/waiter/statsd.clj
  waiter/src/waiter/util/async_utils.clj
  waiter/src/waiter/util/cache_utils.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/http_utils.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/auth/jwt_test.clj
  waiter/test/waiter/cookie_support_test.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/correlation_id_test.clj
  waiter/test/waiter/discovery_test.clj
  waiter/test/waiter/kv_test.clj
  waiter/test/waiter/mocks.clj
  waiter/test/waiter/process_request_test.clj
  waiter/test/waiter/reporters_test.clj
  waiter/test/waiter/scaling_test.clj
  waiter/test/waiter/scheduler/composite_test.clj
  waiter/test/waiter/scheduler/marathon_test.clj
  waiter/test/waiter/schema_test.clj
  waiter/test/waiter/service_test.clj
  waiter/test/waiter/util/async_utils_test.clj
  waiter/test/waiter/util/utils_test.clj
  waiter/test/waiter/websocket_test.clj
  waiter/test/waiter/work_stealing_test.clj
  waiter/test/waiter/zk_test.clj
Labels: internal-green, refactoring

#1113 Instance tracking logs and InstanceTracker Logger
  waiter/resources/log4j.properties
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/src/waiter/state/maintainer.clj
  waiter/src/waiter/state/responder.clj
Labels: internal-green

#1130 fixes typo in :service-d
  waiter/src/waiter/state/maintainer.clj
Labels: internal-green

#1129 renames test-delegate-kill-instance and adds descriptive comments
  waiter/integration/waiter/killed_instance_test.clj
Labels: internal-green, refactoring, test

#1134 reduces test-s3-logs flakiness by allowing more time for second instance to become healthy
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
Labels: flaky-test, internal-green

#1132 avoids assertions on flaky courier behavior of tracking state
  waiter/integration/waiter/grpc_test.clj
Labels: flaky-test, internal-green

#1133 sediment-trailers-support-test: allows for jetty to not use chunked encoding for http/1.1 requests
  waiter/integration/waiter/trailers_test.clj
Labels: flaky-test, internal-green

#1135 test-support-success-gzip-response: allows for jetty to not use chunked encoding for http/1.1 requests
  waiter/integration/waiter/content_encoding_test.clj
Labels: flaky-test, internal-green
