Repository twosigma/waiter, pull requests merged in 2020-03, with the labels that each got.

#1042 sorts nested map parameters to ensure deterministic service-id
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green, wip

#1044 skips test-kubernetes-pod-expiry-grace-period when container-running-grace-secs is 0
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
Labels: flaky-test

#1048 adds guard to protect against NPE when min-instances default is unavailable
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: bug, internal-green

#1049 handles intervening bad descriptors while computing previous descriptor for fallback
  waiter/src/waiter/descriptor.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/descriptor_test.clj
Labels: bug, internal-green

#1050 Adds JWT tests for unknown claims and decoding claims
  containers/test-apps/jwks-server/src/jwks_server/handler.clj
  waiter/bin/ci/jwks-server-setup.sh
  waiter/config-full.edn
  waiter/src/waiter/auth/jwt.clj
  waiter/src/waiter/schema.clj
  waiter/src/waiter/settings.clj
  waiter/test/waiter/auth/jwt_test.clj
Labels: internal-green, test

#1051 adds support for regex validation for JWT iss claim
  waiter/config-full.edn
  waiter/src/waiter/auth/jwt.clj
  waiter/src/waiter/schema.clj
  waiter/test/waiter/auth/jwt_test.clj
Labels: internal-green

#1052 writes new entries before deleting old ones to avoid intervening index queries from reading empty results
  token-syncer/project.clj
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green, refactoring

#1053 adds multiple service streaming test
  waiter/integration/waiter/grpc_test.clj
Labels: internal-green, test

#1054 allows http/2 requests to configure idle timeouts
  waiter/integration/waiter/grpc_test.clj
  waiter/src/waiter/util/http_utils.clj
Labels: bug, internal-green

#1055 adds descriptor to the request log for async status checks
  waiter/src/waiter/handler.clj
  waiter/src/waiter/request_log.clj
Labels: internal-green

#1057 Deflake test-basic-logs
  waiter/integration/waiter/basic_test.clj
Labels: internal-green
