Repository twosigma/waiter, pull requests merged in 2020-08, with the labels that each got.

#1164 adds support for sanitize tokens command
  token-syncer/src/token_syncer/commands/sanitize.clj
  token-syncer/src/token_syncer/main.clj
  token-syncer/test/token_syncer/commands/sanitize_test.clj
  token-syncer/test/token_syncer/waiter_test.clj
Labels: internal-green

#1168 Disable Travis artifact upload to AWS
  .travis.yml
Labels: internal-green

#1170 adds logging to identify tokens with string last update time fields
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green, refactoring

#1171 removes blacklist-on-503 parameter
  waiter/config-full.edn
  waiter/docs/parameters.md
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/killed_instance_test.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/settings.clj
  waiter/test-files/shell-scheduler-backup.json
  waiter/test/waiter/scheduler/shell_test.clj
Labels: internal-green

#1169 adds authorization checks before launching the latest service when fallback is triggered
  waiter/src/waiter/core.clj
  waiter/src/waiter/descriptor.clj
  waiter/test/waiter/descriptor_test.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#1172 adds endpoint to enable oidc automatic registration
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/auth/oidc.clj
  waiter/src/waiter/core.clj
  waiter/test/waiter/auth/oidc_test.clj
Labels: internal-green

#1173 includes exception stack traces in oidc error scenario
  waiter/src/waiter/auth/oidc.clj
  waiter/src/waiter/util/utils.clj
Labels: internal-green

#1176 renames mesos slave to mesos agent
  waiter/config-full.edn
  waiter/config-minimesos.edn
  waiter/src/waiter/handler.clj
  waiter/src/waiter/mesos/mesos.clj
  waiter/src/waiter/scheduler/cook.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/mesos/mesos_test.clj
  waiter/test/waiter/scheduler/marathon_test.clj
Labels: internal-green

#1175 renames blacklist to eject for internal uses
  waiter/config-full.edn
  waiter/docs/parameters.md
  waiter/integration/waiter/busy_instance_test.clj
  waiter/integration/waiter/killed_instance_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/metrics.clj
  waiter/src/waiter/scaling.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/service.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/state/maintainer.clj
  waiter/src/waiter/state/responder.clj
  waiter/src/waiter/work_stealing.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/handler_test.clj
  waiter/test/waiter/scaling_test.clj
  waiter/test/waiter/service_test.clj
  waiter/test/waiter/state/responder_test.clj
Labels: internal-green

#1177 ReplicaSet API version extensions/v1beta1 -> apps/v1
  waiter/config-full.edn
  waiter/src/waiter/settings.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1178 adds the image parameter to the request log
  waiter/src/waiter/request_log.clj
  waiter/test/waiter/request_log_test.clj
Labels: internal-green

#1179 restricts pytest-dist version to <2.0.0
  cli/integration/requirements.txt
Labels: internal-green

#1180 adds server header to cors and saml responses
  waiter/src/waiter/auth/saml.clj
  waiter/src/waiter/cors.clj
  waiter/test/waiter/auth/saml_test.clj
Labels: internal-green

#1181 defends against missing service-id in test-image-field-validation
  waiter/integration/waiter/basic_test.clj
Labels: internal-green, test

#1184 adds support for filtering tokens by run-as-requester and parameterized services
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/token.clj
  waiter/test/waiter/service_description_test.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#1183 adds support for token in the request log for OIDC callback requests
  waiter/src/waiter/auth/oidc.clj
  waiter/src/waiter/request_log.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/auth/oidc_test.clj
  waiter/test/waiter/request_log_test.clj
Labels: internal-green
