Repository twosigma/waiter, pull requests merged in 2020-07, with the labels that each got.

#1144 optimizes token syncer imports
  token-syncer/src/token_syncer/commands/backup.clj
  token-syncer/src/token_syncer/main.clj
  token-syncer/src/token_syncer/spnego.clj
  token-syncer/test/token_syncer/commands/syncer_test.clj
Labels: internal-green, refactoring

#1143 disables test-h2-backend-proto-service on Travis
  waiter/integration/waiter/proto_test.clj
Labels: internal-green, test

#1142 adds support for upgrade-insecure-requests header
  waiter/src/waiter/core.clj
  waiter/test/waiter/core_test.clj
Labels: internal-green

#1145 adds support for restore command
  token-syncer/integration/token_syncer/basic_test.clj
  token-syncer/src/token_syncer/commands/backup.clj
  token-syncer/src/token_syncer/commands/restore.clj
  token-syncer/src/token_syncer/file_utils.clj
  token-syncer/src/token_syncer/main.clj
  token-syncer/test/token_syncer/commands/backup_test.clj
  token-syncer/test/token_syncer/commands/restore_test.clj
Labels: internal-green

#1147 test-basic-priority-support: reduces flakiness due to threads not being scheduled
  waiter/integration/waiter/basic_test.clj
Labels: flaky-test, internal-green

#1140 uses https urls for redirects during OIDC auth
  waiter/src/waiter/auth/oidc.clj
  waiter/test/waiter/auth/oidc_test.clj
Labels: internal-green

#1146 JDK11 upgrade
  .travis.yml
  containers/test-apps/courier/pom.xml
  waiter/integration/waiter/metrics_output_test.clj
  waiter/project.clj
  waiter/src/waiter/main.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/test/waiter/metrics_test.clj
  waiter/test/waiter/scheduler/shell_test.clj
Labels: internal-green

#1148 enables SSL tests after JDK11 migration
  waiter/integration/waiter/proto_test.clj
Labels: internal-green, test

#1149 adds support for disabling kerberos authentication
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/auth/spnego_test.clj
Labels: internal-green

#1150 avoids updating caches for empty responses from prestash cache query
  waiter/src/waiter/auth/kerberos.clj
  waiter/test/waiter/auth/kerberos_test.clj
Labels: bug, internal-green

#1139 add port offset
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1151 avoids reflection warnings
  waiter/integration/waiter/authentication_test.clj
  waiter/test/waiter/test_helpers.clj
Labels: internal-green

#1154 test-concurrency-level: increase responsiveness in scaling down
  waiter/integration/waiter/autoscaling_test.clj
Labels: flaky-test, internal-green

#1155 test-trailers-support-http-proto-sediment: handles cases where jetty converts chunked requests to unchunked
  waiter/integration/waiter/trailers_test.clj
Labels: flaky-test, internal-green

#1153 upgrades Waiter dependencies
  containers/test-apps/courier/pom.xml
  waiter/project.clj
Labels: internal-green

#1157 removes incorrect implementation of upgrade-insecure-requests request header
  waiter/src/waiter/core.clj
  waiter/test/waiter/core_test.clj
Labels: bug, internal-green

#1136 Delay GC of services with stale references based on update time
  waiter/docs/service-references.md
  waiter/src/waiter/core.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/util/descriptor_utils.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#1158 adds logging for consent cookie validation
  waiter/src/waiter/core.clj
  waiter/src/waiter/descriptor.clj
  waiter/src/waiter/service_description.clj
Labels: internal-green

#1152 Envoy sidecar integration
  containers/bin/build-docker-images.sh
  containers/reverse-proxy/Dockerfile
  containers/reverse-proxy/README.md
  containers/reverse-proxy/bin/build-docker-image.sh
  containers/reverse-proxy/envoy-sidecar-example.yaml
  containers/reverse-proxy/envoy-start
  containers/reverse-proxy/envoy.yaml
  waiter/config-full.edn
  waiter/config-k8s.edn
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/schema.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1159 upgrades to jdk11 compatible jet
  containers/test-apps/jwks-server/project.clj
  token-syncer/project.clj
  waiter/project.clj
Labels: internal-green

#1162 handles string ISO date data in token last-update-time
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#1163 Bumps CLI version for 1.0.1 release
  cli/waiter/version.py
Labels: internal-green

#1161 adds support for PDBs for ReplicaSets requiring greater than one min instance
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1165 uses unique names for OIDC auth cookies
  waiter/config-full.edn
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/auth/oidc.clj
  waiter/src/waiter/schema.clj
  waiter/test/waiter/auth/oidc_test.clj
Labels: bug, internal-green
