Repository twosigma/waiter, pull requests merged in 2020-05, with the labels that each got.

#1089 uses http2-hpack from jetty 9.4.28.v20200408 in jet
  waiter/project.clj
Labels: internal-green

#1090 adds support for last-update-time string in admin token update
  cli/integration/tests/waiter/test_cli.py
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#1091 CLI: avoid using user-provided service-description to load cpu and mem
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/querying.py
  cli/waiter/subcommands/show.py
  waiter/src/waiter/handler.clj
Labels: internal-green

#1028 refactor use of run-as-user parameter in service-list-handler
  waiter/src/waiter/handler.clj
  waiter/test/waiter/handler_test.clj
Labels: internal-green, refactoring

#1093 adds support for disabling GC of a service
  waiter/config-full.edn
  waiter/docs/parameters.md
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/scheduler_test.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#1094 adds metric group for the services created in the gRPC integration tests
  waiter/integration/waiter/grpc_test.clj
Labels: internal-green

#1095 extracts the auth server from the JWT authenticator
  waiter/src/waiter/auth/jwt.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/test/waiter/auth/jwt_test.clj
Labels: internal-green, refactoring

#1099 uses thrown-with-msg? instead of thrown? in unit tests
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#1101 avoids complete domain names for tokens created in tests
  waiter/integration/waiter/token_request_test.clj
Labels: internal-green

#1092 Refactor CLI to support plugin overrides from wrapper
  cli/waiter/__main__.py
  cli/waiter/cli.py
  cli/waiter/configuration.py
  cli/waiter/http_util.py
  cli/waiter/version.py
Labels: internal-green

#1098 treat same content edits from users as successful token sync
  token-syncer/integration/token_syncer/basic_test.clj
  token-syncer/src/token_syncer/commands/syncer.clj
  token-syncer/test/token_syncer/commands/syncer_test.clj
Labels: internal-green

#1102 adds support for filtering tokens list by specific parameter values
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#1097 adds x-waiter-jwt header containing JWT access token to backend requests
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/auth/jwt.clj
  waiter/src/waiter/auth/kerberos.clj
  waiter/src/waiter/auth/saml.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/headers.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/util/utils.clj
  waiter/src/waiter/websocket.clj
  waiter/test/waiter/async_request_test.clj
  waiter/test/waiter/auth/authenticator_test.clj
  waiter/test/waiter/auth/jwt_test.clj
Labels: internal-green

#1100 disallows x-waiter-idle-timeout-mins header to have a value of zero
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/service_description.clj
Labels: internal-green

#1104 marks test_show_services_using_token as xfail
  cli/integration/tests/waiter/test_cli.py
Labels: flaky-test

#1103 allows token metadata to be used in search queries
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#1105 Require pytest<=5.3.5
  cli/integration/requirements.txt
Labels: internal-green

#1106 adds support for async requests in http-utils
  waiter/src/waiter/util/http_utils.clj
  waiter/test/waiter/util/http_utils_test.clj
Labels: internal-green, refactoring

#1107 introduces JWT validator
  waiter/src/waiter/auth/jwt.clj
  waiter/src/waiter/core.clj
  waiter/test/waiter/auth/jwt_test.clj
Labels: internal-green, refactoring
