Repository twosigma/waiter, pull requests merged in 2021-09, with the labels that each got.

#1438 Fix test-service-account-injection for default-namespace
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
Labels: internal-green

#1439 Support more Envoy configurations
  containers/reverse-proxy/Dockerfile
  containers/reverse-proxy/envoy-one-port.yaml
  containers/reverse-proxy/envoy-sidecar-example.yaml
  containers/reverse-proxy/envoy-start
  containers/reverse-proxy/envoy-two-ports.yaml
  containers/reverse-proxy/envoy.template.yaml
Labels: internal-green

#1440 searches for container in statuses instead of relying on implicit positions
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: bug, internal-green

#1443 adds support for periodically refreshing the statsd host IP
  waiter/src/waiter/settings.clj
  waiter/src/waiter/statsd.clj
  waiter/test/waiter/statsd_test.clj
Labels: internal-green

#1437 Rename Waiter's Envoy reverse proxy sidecar to Raven
  containers/bin/build-docker-images.sh
  containers/raven/Dockerfile
  containers/raven/README.md
  containers/raven/bin/build-docker-image.sh
  containers/raven/envoy.template.yaml
  containers/raven/raven-start
  waiter/config-full.edn
  waiter/config-k8s.edn
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/grpc_test.clj
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/integration/waiter/request_timeout_test.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/schema.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1444 adds logging for resolved IP address
  waiter/src/waiter/statsd.clj
Labels: internal-green

#1442 improves messaging in the test-identical-version assertion
  waiter/integration/waiter/basic_test.clj
Labels: internal-green

#1441 ensures all routers are aware of healthy instances in test-list-apps
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: flaky-test, internal-green

#1445 adds support for periodically refreshing the graphite reporter host IP
  waiter/src/waiter/reporter.clj
  waiter/test/waiter/reporters_test.clj
Labels: internal-green

#1342 Enable TLS termination by Raven sidecar
  containers/raven/raven-start
  containers/test-apps/kitchen/bin/kitchen
  containers/test-apps/nginx/bin/run-nginx-server.sh
  containers/test-apps/nginx/data/nginx-template.conf
  waiter/config-full.edn
  waiter/config-k8s.edn
  waiter/integration/waiter/deployment_errors_test.clj
  waiter/integration/waiter/grpc_test.clj
  waiter/integration/waiter/request_timeout_test.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/schema.clj
  waiter/src/waiter/status_codes.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1446 Use keywords for port->protocol map keys
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1447 adds support for validating cmd-type in profile defaults
  waiter/src/waiter/core.clj
  waiter/src/waiter/service_description.clj
Labels: bug, internal-green

#1449 Use ubuntu-latest version in GitHub Actions CI
  .github/workflows/cli-integration.yml
  .github/workflows/integration-fast.yml
  .github/workflows/integration-slow.yml
  .github/workflows/test-apps.yml
  .github/workflows/token-syncer.yml
  .github/workflows/unit-tests.yml
Labels: internal-green

#1448 fixes a bug in comparing datetime strings
  README.md
  waiter/integration/waiter/reporters_integration_test.clj
Labels: bug, internal-green

#1450 ensures services accessed directly be service-ID get stale GC-ed
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#1451 adds support for date parsing in settings files
  waiter/src/waiter/settings.clj
  waiter/test-files/test-bar.edn
  waiter/test/waiter/settings_test.clj
Labels: internal-green
