Repository twosigma/waiter, pull requests merged in 2021-04, with the labels that each got.

#1320 Cli Fix SSH Subcommand not getting instances of service from multiple clusters
  cli/integration/tests/waiter/test_cli.py
  cli/integration/tests/waiter/test_cli_multi_cluster.py
  cli/integration/tests/waiter/util.py
  cli/waiter/subcommands/ssh.py
Labels: internal-green

#1321 CLI tests use tty env variable instead of actual tty
  cli/integration/tests/waiter/cli.py
  cli/waiter/terminal.py
Labels: internal-green

#1324 Add more token watch logs and correlate them throughout event flow
  waiter/src/waiter/token.clj
  waiter/src/waiter/token_watch.clj
  waiter/test/waiter/token_watch_test.clj
Labels: internal-green

#1325 Release cli 1.2.3
  cli/waiter/version.py
Labels: internal-green

#1314 Add service level deployment errors when failing k8s api requests
  waiter/config-full.edn
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/service.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/state/maintainer.clj
  waiter/src/waiter/util/cache_utils.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
  waiter/test/waiter/util/utils_test.clj
Labels: internal-green

#1327 consumes request stream asynchronously with reduced young gen memory pressure
  waiter/integration/waiter/streaming_test.clj
  waiter/src/waiter/main.clj
Labels: bug, internal-green

#1329 makes draining request bytes buffer size configurable
  waiter/config-full.edn
  waiter/src/waiter/main.clj
  waiter/src/waiter/settings.clj
Labels: internal-green

#1330 Don't create deployment error if k8s 409 conflict
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: internal-green

#1331 changes order of failed response test in streaming-test
  waiter/integration/waiter/streaming_test.clj
Labels: internal-green

#1333 log rotation every hour
  waiter/resources/log4j.properties
Labels: internal-green

#1334 introduces query parameter to exclude inter-router syncing for ping
  waiter/integration/waiter/health_check_test.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#1335 avoids logging stack trace for deployment errors
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/service.clj
Labels: internal-green

#1336 Gate k8s scheduler initialization on watch states
  waiter/config-full.edn
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1337 always includes service-id in service-state for waiter-ping output
  waiter/integration/waiter/health_check_test.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#1340 ensures termination of responder go block in unit tests
  waiter/src/waiter/state/responder.clj
  waiter/test/waiter/state/responder_test.clj
Labels: flaky-test, internal-green

#1339 tags waiter error responses with an error class for the request-log
  waiter/src/waiter/auth/kerberos.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/process_request.clj
  waiter/test/waiter/auth/spnego_test.clj
Labels: internal-green

#1343 adds support for including healthy instances in /apps endpoint
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/handler.clj
  waiter/test/waiter/handler_test.clj
Labels: internal-green

#1344 add async version of exponential backoff retry strategy
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/util/utils_test.clj
Labels: internal-green

#1345 Add proxy support http util
  waiter/src/waiter/util/http_utils.clj
Labels: internal-green
