Repository twosigma/waiter, pull requests merged in 2021-08, with the labels that each got.

#1408 supports regexes in token list queries
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/token.clj
Labels: internal-green

#1410 supports forcing authenticated health checks in k8s scheduled services
  waiter/config-full.edn
  waiter/config-k8s.edn
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/composite.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
  waiter/test/waiter/scheduler/marathon_test.clj
  waiter/test/waiter/scheduler/shell_test.clj
  waiter/test/waiter/scheduler_test.clj
Labels: internal-green

#1411 CLI release 1.4.1
  cli/waiter/version.py
Labels: internal-green

#1413 Revert "supports regexes in token list queries"
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/token.clj
Labels: internal-green

#1415 ensures unique version of services per integration test run
  waiter/integration/waiter/health_check_test.clj
  waiter/integration/waiter/token_request_test.clj
Labels: bug, internal-green, test

#1414 adds tracking of containers in the k8s service object
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1416 adds --no-wait flag to maintenance stop
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/subcommands/maintenance.py
Labels: cli, internal-green

#1417 adds support for CLI start and stop commands
  cli/integration/tests/waiter/cli.py
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/cli.py
  cli/waiter/subcommands/maintenance.py
Labels: cli, internal-green

#1418 skips checking for maintenance mode being activated on start/maintenance stop commands
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/subcommands/maintenance.py
Labels: cli, internal-green

#1419 fixes reference to default namespace in k8s scheduler factory function
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: bug, internal-green

#1421 enables server reflection in courier
  containers/test-apps/courier/pom.xml
  containers/test-apps/courier/src/main/java/com/twosigma/waiter/courier/GrpcServer.java
Labels: internal-green

#1423 fix grpc server cancel handling
  waiter/src/waiter/process_request.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#1424 Cli release v 1.5.0
  cli/waiter/version.py
Labels: cli, internal-green

#1428 ensures deletion of all tokens created in test-service-list-filtering
  waiter/integration/waiter/token_request_test.clj
Labels: test, internal-green

#1427 adds missing metric group to integration tests
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: test, internal-green

#1426 changes test token names to c<timestamp>-w8r-<suffix> pattern
  waiter/src/waiter/util/client_tools.clj
Labels: test, internal-green

#1425 Adds support for determining the creation time of a service
  waiter/src/waiter/core.clj
  waiter/src/waiter/kv.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/kv_test.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#1431 Fix streaming timeout integration test to start timing from receiving initial event
  waiter/integration/waiter/instance_tracker_integration_test.clj
  waiter/integration/waiter/token_watch_integration_test.clj
Labels: internal-green

#1430 adds revision version annotation to replicaset spec
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1429 adds authorization to service logs display
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/authorization.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/authorization_test.clj
  waiter/test/waiter/core_test.clj
Labels: internal-green

#1432 avoids service entry tokens from preventing stale gc of services
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
Labels: bug, internal-green

#1433 makes the function to determine namespace configurable
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: refactoring, internal-green

#1436 adds pod spec metadata annotations into the Service object
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1435 adds support for context in replicaset-spec-builder-fn
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green
