Repository twosigma/waiter, pull requests merged in 2021-11, with the labels that each got.

#1458 Fix type confusion when SPNEGO completes with no response
  waiter/src/waiter/auth/spnego.clj
Labels: internal-green

#1469 make tls deployment error tests explicit (flaky)
  waiter/integration/waiter/deployment_errors_test.clj
Labels: internal-green

#1468 Token syncer: sync when user editable token fields are the same even when mismatching metadata fields
  token-syncer/integration/token_syncer/basic_test.clj
  token-syncer/src/token_syncer/commands/syncer.clj
  token-syncer/test/token_syncer/commands/syncer_test.clj
Labels: internal-green

#1470 computes the service-id using compute-descriptor function in consent handler
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/test/waiter/handler_test.clj
Labels: bug, internal-green

#1467 adds support for ping after kill operation
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/action.py
  cli/waiter/subcommands/kill.py
  cli/waiter/subcommands/ping.py
Labels: internal-green

#1461 improves logic to determine when exclusive mode is enabled
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/util/client_tools.clj
Labels: bug, internal-green

#1464 adds delay while sending chunked requests in integration test
  waiter/integration/waiter/basic_test.clj
Labels: flaky-test, internal-green

#1471 reduces JWT cookie expiry time in strict mode by a configurable amount
  waiter/src/waiter/auth/oidc.clj
  waiter/test/waiter/auth/oidc_test.clj
Labels: internal-green

#1473 Add a test that sets the origin header on a websocket request
  waiter/integration/waiter/websocket_integration_test.clj
Labels: internal-green

#1475 moves service-mapping logic to ServiceDescriptionBuilder build() function
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/descriptor_test.clj
  waiter/test/waiter/service_description_test.clj
Labels: refactoring, internal-green

#1476 adds access-control headers to response for CORS expires-at requests
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/cors.clj
  waiter/src/waiter/util/client_tools.clj
Labels: internal-green

#1479 includes java version in server info block
  waiter/src/waiter/handler.clj
Labels: internal-green

#1474 adds type and restart count to k8s container statuses
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1478 adds support for default service-mapping that dynamically determines when to use exclusive mode
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/config.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/settings.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green
