Repository twosigma/waiter, pull requests merged in 2021-06, with the labels that each got.

#1363 Release cli 1.3.0
  cli/waiter/version.py
Labels: internal-green

#1361 makes the syncer output terser by reducing number of lines output
  token-syncer/src/token_syncer/commands/syncer.clj
Labels: internal-green

#1364 avoids dependency on functioning statsd server
  waiter/integration/waiter/reporters_integration_test.clj
Labels: internal-green, test

#1362 adds support for including service-id in tokens output
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/descriptor.clj
  waiter/src/waiter/token.clj
  waiter/test/waiter/descriptor_test.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#1366 handles signature change issues from merging concurrent MRs
  waiter/test/waiter/token_test.clj
Labels: internal-green

#1367 Add unsupported headers
  waiter/config-full.edn
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/websocket_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/util/utils.clj
  waiter/src/waiter/websocket.clj
  waiter/test/waiter/auth/authenticator_test.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#1370 adds support for including the cluster in the /tokens output
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#1354 adds support for opting out of token syncing when metadata is configured
  token-syncer/integration/token_syncer/basic_test.clj
  token-syncer/src/token_syncer/commands/syncer.clj
  token-syncer/test/token_syncer/commands/syncer_test.clj
Labels: internal-green

#1369 Refactor handle-post-token-request function to use a validator component
  waiter/config-full.edn
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/token.clj
  waiter/src/waiter/token_validator.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green, refactoring

#1374 Watch healthy instances endpoint
  waiter/integration/waiter/instance_tracker_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/instance_tracker.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/token_watch.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/instance_tracker_test.clj
  waiter/test/waiter/token_watch_test.clj
Labels: internal-green
