Repository twosigma/waiter, pull requests merged in 2021-02, with the labels that each got.

#1281 CORS access-control-request-headers is optional
  waiter/src/waiter/cors.clj
  waiter/test/waiter/cors_test.clj
Labels: bug, internal-green

#1282 adds dual flags to allow or disallow overrides
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/token_post.py
Labels: internal-green

#1283 refactors ping methods into action.py
  cli/waiter/action.py
  cli/waiter/subcommands/ping.py
Labels: internal-green, refactoring

#1284 refactors kill methods into action.py
  cli/waiter/action.py
  cli/waiter/subcommands/kill.py
Labels: internal-green, refactoring

#1287 renders nil keys while rendering maps as json
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/util/utils_test.clj
Labels: internal-green

#1285 handles NPE while deleting frequently restarting pods
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: bug, internal-green

#1286 adds flag to restrict k8s scheduler syncer-state output
  waiter/src/waiter/scheduler/cook.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/marathon.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/test/waiter/scheduler/cook_test.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1288 avoids creating separate scheduler-config to address circular dependency
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: bug, internal-green

#1279 adds support for ping/kill during maintenance stop/start
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/action.py
  cli/waiter/subcommands/maintenance.py
Labels: internal-green

#1276 Token Watch
  waiter/config-full.edn
  waiter/integration/waiter/token_watch_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/token.clj
  waiter/src/waiter/token_watch.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/token_test.clj
  waiter/test/waiter/token_watch_test.clj
Labels: internal-green

#1290 adds logging and connection metric to token watch connections
  waiter/src/waiter/token.clj
  waiter/src/waiter/token_watch.clj
Labels: internal-green

#1293 adds jetty version to the status output
  waiter/src/waiter/handler.clj
Labels: internal-green

#1291 configures the scanning interval to detect changes to and reload the keystore
  waiter/config-full.edn
  waiter/src/waiter/settings.clj
Labels: internal-green

#1294 adds support for streaming timeout on token watch
  waiter/integration/waiter/token_watch_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/token.clj
  waiter/test/waiter/token_test.clj
Labels: internal-green

#1296 configures queue timeout to control wait time for ping from CLI
  cli/waiter/action.py
Labels: bug, cli, internal-green
