Repository twosigma/waiter, pull requests merged in 2022-08, with the labels that each got.

#1613 Rename core-service-description to service-description in endpoint
  waiter/integration/waiter/token_history_integration_test.clj
  waiter/src/waiter/descriptor.clj
  waiter/test/waiter/token_history_test.clj
Labels: internal-green

#1615 upgrades to jetty version 9.4.48.v20220622
  waiter/project.clj
Labels: internal-green

#1619 Reverts "upgrade to jetty version 9.4.48.v20220622"
  waiter/project.clj
Labels: internal-green

#1625 adds service description validation to override api
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#1627 handles assertion errors in thrown from scale-service
  waiter/src/waiter/scaling.clj
  waiter/test/waiter/scaling_test.clj
Labels: bug, internal-green

#1628 mark flakey metrics sync integration test as explicit
  waiter/integration/waiter/metrics_sync_integration_test.clj
Labels: internal-green

#1629 ensures scale-service handles integer values during scaling
  waiter/src/waiter/scaling.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scaling_test.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: bug

#1630 Fix cluster calculation in token integration test
  waiter/integration/waiter/token_request_test.clj
Labels: internal-green

#1560 adds correlation ids to k8s api requests and scheduler logs
  waiter/src/waiter/correlation_id.clj
Labels: internal-green

#1618 Configurable liveness checks
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/liveness_check_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/auth/authenticator_test.clj
  waiter/test/waiter/descriptor_test.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
  waiter/test/waiter/service_description_test.clj
  waiter/test/waiter/token_history_test.clj
Labels: internal-green

#1631 makes the token auth failure message configurable
  cli/integration/tests/waiter/test_cli.py
  waiter/src/waiter/settings.clj
  waiter/src/waiter/token_validator.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/token_test.clj
  waiter/test/waiter/util/utils_test.clj
Labels: internal-green
