Repository twosigma/waiter, pull requests merged in 2022-09, with the labels that each got.

#1636 deflakes test-grace-period-disabled by checking instance health from responder state
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: flaky-test, internal-green

#1652 promotes common request timeout headers to token parameters
  waiter/config-full.edn
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/util/date_utils.clj
  waiter/src/waiter/util/http_utils.clj
  waiter/test/waiter/process_request_test.clj
  waiter/test/waiter/service_description_test.clj
Labels: internal-green

#1654 adds support for reporting backend connect errors
  waiter/config-full.edn
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/settings.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#1653 add pod preStop command for more graceful termination of pod
  waiter/config-full.edn
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/settings.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1656 adds labels to logs from classify-error for simplified debugging
  waiter/src/waiter/process_request.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#1655 adds support for tracking grpc-response headers
  waiter/src/waiter/process_request.clj
Labels: internal-green

#1659 handles NPE in cookie decoding
  waiter/src/waiter/cookie_support.clj
  waiter/test/waiter/cookie_support_test.clj
Labels: bug, internal-green

#1660 reports 403 error on OIDC too many cookies
  waiter/src/waiter/auth/oidc.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/test/waiter/auth/oidc_test.clj
  waiter/test/waiter/auth/spnego_test.clj
Labels: internal-green

#1661 makes the 401 error message configurable
  waiter/config-full.edn
  waiter/integration/waiter/grpc_test.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/settings.clj
  waiter/test/waiter/auth/spnego_test.clj
Labels: internal-green

#1662 moves maintenance mode handling earlier in the ping handler chain
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/health_check_test.clj
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/process_request.clj
Labels: internal-green

#1666 fixes too many cookies response code
  waiter/integration/waiter/authentication_test.clj
Labels: internal-green
