Repository twosigma/waiter, pull requests merged in 2022-04, with the labels that each got.

#1542 default to consistent ssl-validation on k8s api requests
  waiter/config-full.edn
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: internal-green

#1543 record timeout exceptions for deployment errors
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/state/maintainer.clj
  waiter/test/waiter/state/maintainer_test.clj
Labels: internal-green

#1544 skips cors check for health checks from ping requests
  waiter/src/waiter/cors.clj
  waiter/src/waiter/process_request.clj
  waiter/test/waiter/cors_test.clj
Labels: bug, internal-green

#1541 adds kv-store-factory to the token-validator context
  waiter/src/waiter/core.clj
Labels: internal-green

#1545 reverts websocket backpressure support
  waiter/project.clj
Labels: internal-green

#1547 updates dependency versions to avoid conflicts
  waiter/project.clj
Labels: internal-green

#1548 reduces failures in current unit tests when run concurrently on the same host
  waiter/test/waiter/scheduler/kubernetes_test.clj
  waiter/test/waiter/scheduler/shell_test.clj
Labels: internal-green

#1552 throw exception on k8s wait-for-watches timeout
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: bug, internal-green

#1553 adds support for clearing failed instances when service is deleted in k8s scheduler
  waiter/integration/waiter/kubernetes_scheduler_integration_test.clj
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: internal-green

#1555 fix races and flaky tests in shell scheduler
  waiter/src/waiter/scheduler/shell.clj
  waiter/test/waiter/scheduler/shell_test.clj
Labels: internal-green

#1551 avoids marking killed instances as failed instances by tracking kill candidates
  waiter/src/waiter/handler.clj
  waiter/src/waiter/scaling.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/handler_test.clj
  waiter/test/waiter/scaling_test.clj
  waiter/test/waiter/scheduler_test.clj
Labels: internal-green

#1557 Waiter ssh to use --context instead of --server when possible
  cli/integration/tests/waiter/util.py
  cli/waiter/subcommands/ssh.py
Labels: internal-green

#1521 cli: add additional-clusters field for local config
  cli/README.md
  cli/waiter/configuration.py
Labels: internal-green

#1556 removes support for USE_BEARER_AUTH env variable
  waiter/config-full.edn
  waiter/integration/waiter/authentication_test.clj
  waiter/src/waiter/auth/jwt.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/test/waiter/auth/jwt_test.clj
Labels: internal-green

#1558 responds 2XX for waiter pings by wrapping descriptor errors in nested response
  cli/waiter/action.py
  waiter/integration/waiter/health_check_test.clj
  waiter/integration/waiter/token_request_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/descriptor.clj
  waiter/src/waiter/process_request.clj
  waiter/test/waiter/descriptor_test.clj
  waiter/test/waiter/process_request_test.clj
Labels: internal-green

#1559 fixes error message reporting in k8s watch
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: internal-green

#1526 Add ability to consume external metrics for last request time
  waiter/config-full.edn
  waiter/integration/waiter/authentication_test.clj
  waiter/integration/waiter/instance_tracker_integration_test.clj
  waiter/integration/waiter/token_watch_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/descriptor.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/metrics_consumer.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/date_utils.clj
  waiter/src/waiter/util/http_utils.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/metrics_consumer_test.clj
  waiter/test/waiter/scheduler_test.clj
  waiter/test/waiter/util/utils_test.clj
Labels: internal-green

#1562 Add GitHub Action to publish waiter cli package to pypi on new release tag pushed
  .github/workflows/cd-waiter-cli.yml
Labels: internal-green

#1563 Bumps CLI version for 1.5.2 release
  cli/waiter/version.py
Labels: internal-green

#1561 uses timeout channels to await responses on channels
  waiter/test/waiter/state/responder_test.clj
  waiter/test/waiter/test_helpers.clj
Labels: flaky-test, internal-green
