Repository twosigma/waiter, pull requests merged in 2022-07, with the labels that each got.

#1598 adds support for periodically generating thread dumps
  waiter/config-full.edn
  waiter/resources/log4j.properties
  waiter/src/waiter/core.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/util/thread_dump.clj
Labels: internal-green

#1599 Revert "retrieves instance start time from main container status"
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1602 changes blocking sleep to async sleep
  waiter/src/waiter/scheduler/kubernetes.clj
Labels: refactoring, internal-green

#1600 retrieves instance start time from main container status
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/test/waiter/scheduler/kubernetes_test.clj
Labels: internal-green

#1603 allow for other proxies in the `via` header test
  waiter/integration/waiter/basic_test.clj
Labels: internal-green

#1606 Respect ignore-disabled-auth in kerberos middleware
  waiter/src/waiter/auth/spnego.clj
  waiter/test/waiter/auth/spnego_test.clj
Labels: internal-green

#1607 Fix metrics sync integration test to work in multi router scenarios by forcing distribution scheme simple
  waiter/integration/waiter/metrics_sync_integration_test.clj
Labels: internal-green

#1610 removes waiter auth cookies from backend response
  waiter/integration/waiter/cookie_support_integration_test.clj
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/headers.clj
  waiter/src/waiter/process_request.clj
  waiter/test/waiter/auth/authenticator_test.clj
  waiter/test/waiter/headers_test.clj
Labels: bug, internal-green

#1611 Add comprehensive token history
  waiter/integration/waiter/token_history_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/descriptor.clj
  waiter/src/waiter/handler.clj
  waiter/test/waiter/token_history_test.clj
Labels: internal-green
