Repository twosigma/waiter, pull requests merged in 2022-10, with the labels that each got.

#1669 adds waiter token for 401 and 403 responses to the request log
  waiter/src/waiter/auth/authentication.clj
  waiter/src/waiter/auth/jwt.clj
  waiter/src/waiter/auth/oidc.clj
  waiter/src/waiter/auth/spnego.clj
  waiter/src/waiter/cors.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/util/utils_test.clj
Labels: internal-green

#1670 handles race between registration and deregistration of metrics syncer websockets
  waiter/src/waiter/metrics_sync.clj
  waiter/test/waiter/metrics_sync_test.clj
Labels: internal-green

#1674 https://github.com/twosigma/waiter/issues/1637
  cli/integration/tests/waiter/test_cli.py
  cli/waiter/subcommands/ssh.py
Labels: capstone-2022

#1673 adds support for hard-deleting sync opt-out tokens
  token-syncer/integration/token_syncer/basic_test.clj
  token-syncer/src/token_syncer/commands/syncer.clj
  token-syncer/test/token_syncer/commands/syncer_test.clj
Labels: internal-green

#1676 avoids reporting error while syncing deleted short-lived tokens
  token-syncer/src/token_syncer/commands/syncer.clj
  token-syncer/test/token_syncer/commands/syncer_test.clj
Labels: internal-green, improvement

#1664 upgrades to jetty version 9.4.49.v20220914
  waiter/project.clj
Labels: internal-green

#1675 Added service scaling state to the show CLI command
  cli/integration/tests/waiter/test_cli.py
  cli/integration/tests/waiter/test_cli_multi_cluster.py
  cli/waiter/display.py
  cli/waiter/subcommands/show.py
Labels: capstone-2022
