Repository twosigma/waiter, pull requests merged in 2023-01, with the labels that each got.

#1692 refactors token watch integration tests to move macros to client tools
  waiter/integration/waiter/token_watch_integration_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: refactoring, test

#1694 adds API endpoint for sending sigkill and sigterm signals to instances
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/shell_scheduler_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/handler.clj
  waiter/src/waiter/scheduler.clj
  waiter/src/waiter/scheduler/composite.clj
  waiter/src/waiter/scheduler/kubernetes.clj
  waiter/src/waiter/scheduler/shell.clj
  waiter/src/waiter/status_codes.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/handler_test.clj
  waiter/test/waiter/scheduler/shell_test.clj
Labels: internal-green, capstone-2022

#1696 upgrades python for github actions to 3.9
  .github/workflows/cd-waiter-cli.yml
  .github/workflows/cli-integration.yml
  .github/workflows/test-apps.yml
Labels: internal-green, regression

#1697 cleans up import order
  cli/waiter/cli.py
Labels: internal-green

#1693 refactors instance selection logic in CLI ssh
  cli/waiter/instance_select.py
  cli/waiter/subcommands/ssh.py
Labels: refactoring, internal-green, capstone-2022

#1698 increases timeout and improves debug assertion in failing unit test t…
  waiter/test/waiter/metrics_sync_test.clj
Labels: flaky-test, internal-green

#1695 adds support to CLI for instance kill
  cli/integration/tests/waiter/cli.py
  cli/integration/tests/waiter/test_cli.py
  cli/integration/tests/waiter/util.py
  cli/waiter/action.py
  cli/waiter/cli.py
  cli/waiter/subcommands/instance.py
  waiter/src/waiter/handler.clj
  waiter/test/waiter/handler_test.clj
Labels: cli, internal-green, capstone-2022

#1699 fixes test-basic-health-check-port-index for shell scheduler
  waiter/integration/waiter/basic_test.clj
  waiter/src/waiter/util/client_tools.clj
Labels: flaky-test, internal-green

#1691 reference updates support on tokens endpoint
  waiter/integration/waiter/token_request_test.clj
  waiter/integration/waiter/token_watch_integration_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/service_description.clj
  waiter/src/waiter/token.clj
  waiter/src/waiter/token_watch.clj
  waiter/src/waiter/util/client_tools.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/core_test.clj
  waiter/test/waiter/scheduler_test.clj
  waiter/test/waiter/service_description_test.clj
  waiter/test/waiter/token_test.clj
  waiter/test/waiter/token_watch_test.clj
Labels: internal-green

#1701 makes the reserve instance channel buffer size dynamically configurable
  waiter/config-full.edn
  waiter/src/waiter/service.clj
  waiter/src/waiter/settings.clj
  waiter/src/waiter/state/responder.clj
  waiter/src/waiter/status_codes.clj
  waiter/src/waiter/util/utils.clj
  waiter/test/waiter/util/utils_test.clj
Labels: bug, internal-green

#1703 fixes assumption that only run-as-user=* is run-as-requester service
  waiter/src/waiter/service_description.clj
  waiter/test/waiter/service_description_test.clj
  waiter/test/waiter/token_test.clj
Labels: bug, internal-green

#1705 prioritizes ping requests over queued proxy requests
  waiter/integration/waiter/basic_test.clj
  waiter/integration/waiter/health_check_test.clj
  waiter/src/waiter/core.clj
  waiter/src/waiter/process_request.clj
  waiter/src/waiter/util/async_utils.clj
  waiter/test/waiter/process_request_test.clj
  waiter/test/waiter/util/async_utils_test.clj
Labels: internal-green

#1710 add log line when owner attempts token update
  waiter/src/waiter/token_validator.clj
Labels: internal-green
